---
title: "Introduction to R"
output: html_notebook
---

# Worcester Election Data
This data is from [City of Worcester Open GIS](https://gisdata.worcesterma.gov/)

This section will show where Worcester precincts and voting locations are.

```{r}
library(sf)      # here we tell R that we need the Simple Features library (sf)
library(tmap)    # for static and interactive maps
library(leaflet) # for interactive maps
library(ggplot2) # tidyverse data visualization package

#then we create an object called "precs," which is short for precincts and fill it with the data from our geojson file
precs = read_sf("data/Voting_Precincts_Based_on_2020_Census_Data.geojson")

#the "head" function tells us what is in the object and what kind of object it is
head(precs)

#let's plot our object
tm_shape(precs) + 
  tm_fill()

#now let's try it with some borders
tm_shape(precs) + 
  tm_fill() +
  tm_borders()

#what about some labels?
tm_shape(precs) + 
  tm_fill(col = "springgreen2") +
  tm_borders(col = "purple") +  
  tm_text("Ward_Precinct", size="AREA", col = "violetred2")

#that didn't work? how do we learn more about our tm_* (tmap) functions?
?tmap

#R will let you make a map object and reuse it
woo_map1 = tm_shape(precs) + 
  tm_fill(col = "springgreen2") +
  tm_borders(col = "purple") +  
  tm_text("Ward_Precinct", size="AREA", col = "violetred2")

woo_map1
```

## Polling Stations 
Your task is to make a new section that imports the voting polling stations and places them on a map.
```{r}
polls = read_sf("data/Polling_Locations.geojson")

woo_map2 = tm_shape(polls) +
  tm_symbols()

woo_map1+woo_map2



```



